[package]
name = "ocaml-interop"
version = "0.4.4" # remember to update html_root_url
authors = ["Bruno Deferrari <utizoc@gmail.com>"]
license = "MIT"
description = "Utilities for Rust and OCaml interoperability"
homepage = "http://github.com/simplestaking/ocaml-interop"
repository = "http://github.com/simplestaking/ocaml-interop"
keywords = ["ocaml", "rust", "ffi", "interop"]
edition = "2018"
exclude = [
    ".github/*",
]

[package.metadata.docs.rs]
features = [ "docs-rs" ]

[dependencies]
ocaml-sys = "0.18.1"

[features]
docs-rs = ["ocaml-sys/docs-rs"]
without-ocamlopt = ["ocaml-sys/without-ocamlopt"]
